input {
  syslog {
    port => 5001
    type => "syslog_plain"
    codec => multiline {
      pattern => "^<.+>.*?\d{4}-\d{2}-\d{2} "
      negate => true
      what => "previous"
    }
  }
  syslog {
    port => 5002
    type => "syslog_json"
  }
}

filter {
  if [type] == "syslog_json" {
    json {
      source => "message"
    }
    mutate {
      add_field => { "environment" => "docker" }
    }
    if [timestamp] {
      date {
        match => [ "timestamp", "ISO8601" ]
        target => "@timestamp"
      }
    }
  }
  if [type] == "syslog_plain" {
    mutate {
      gsub => [ "message", "\n<.+?>.*?:\s", " " ]
    }
    mutate {
      gsub => [ "message", "\t+", " ", "message", "\s+", " " ]
    }
    mutate {
      add_field => {
        "service" => "%{tag}"
        "environment" => "docker"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
  }
}
