spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT}

logging:
  level:
    root: INFO
    org.example: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.cloud.openfeign: DEBUG

feign:
  micrometer:
    enabled: true

user:
  url: ${USER_SERVICE_URL}
  connectTimeout: 5000
  readTimeout: 5000
  loggerLevel: FULL
