spring.application.name=dz7-app
server.port=8080

spring.datasource.url=jdbc:postgresql://db:5432/db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces

logging.level.root=INFO
logging.level.org.example.dz7=DEBUG
